WITH CUST_MONTH AS ( 
    SELECT DISTINCT CUST_CODE, DATE_TRUNC(PARSE_DATE('%Y%m%d', CAST(SHOP_DATE AS STRING)), MONTH) SHOP_MONTH 
    FROM `hybrid-chassis-336814.sample_dataset.supermarket` 
    WHERE CUST_CODE IS NOT NULL ) 
SELECT REPORT_MONTH ,
    COUNT(DISTINCT CASE WHEN STATUS = 'NEW' THEN CUST_CODE ELSE NULL END) AS NEW_CUSTOMER ,
    COUNT(DISTINCT CASE WHEN STATUS = 'REPEAT' THEN CUST_CODE ELSE NULL END) AS REPEAT_CUSTOMER ,
    COUNT(DISTINCT CASE WHEN STATUS = 'REACTIVATED' THEN CUST_CODE ELSE NULL END) AS REACTIVATED_CUSTOMER ,
    -COUNT(DISTINCT CASE WHEN STATUS = 'CHURNED' THEN CUST_CODE ELSE NULL END) AS CHURNED_CUSTOMER 
FROM ( 
    SELECT CUST_CODE, SHOP_MONTH AS REPORT_MONTH, PREV_MONTH ,
      CASE 
        WHEN DATE_DIFF(SHOP_MONTH, PREV_MONTH, MONTH) IS NULL THEN 'NEW' 
        WHEN DATE_DIFF(SHOP_MONTH, PREV_MONTH, MONTH) = 1 THEN 'REPEAT' 
        WHEN DATE_DIFF(SHOP_MONTH, PREV_MONTH, MONTH) > 1 THEN 'REACTIVATED' 
      ELSE NULL END AS STATUS 
    FROM ( 
            SELECT CUST_CODE, SHOP_MONTH, LAG(SHOP_MONTH, 1) OVER (PARTITION BY CUST_CODE ORDER BY SHOP_MONTH) AS PREV_MONTH 
            FROM CUST_MONTH ) 
        UNION ALL 
        SELECT CUST_CODE, DATE_ADD(SHOP_MONTH, INTERVAL 1 MONTH) REPORT_MONTH, SHOP_MONTH as PREV_MONTH ,'CHURNED' AS STATUS 
        FROM ( 
            SELECT CUST_CODE, SHOP_MONTH ,
                LEAD(SHOP_MONTH, 1) OVER (PARTITION BY CUST_CODE ORDER BY SHOP_MONTH) AS NEXT_TRANS_DATE ,
                DATE_DIFF(LEAD(SHOP_MONTH, 1) OVER (PARTITION BY CUST_CODE ORDER BY SHOP_MONTH), SHOP_MONTH, MONTH) AS N_MONTH 
            FROM CUST_MONTH ) 
            WHERE (N_MONTH > 1 or N_MONTH is null) AND SHOP_MONTH < (SELECT MAX(SHOP_MONTH) FROM CUST_MONTH) ) 
GROUP BY REPORT_MONTH 
ORDER BY REPORT_MONTH ; 
